### PR TITLE
Fix CRC32 peripheral

### LINKED ISSUE #281: CRC32 always emits zero when fed bytes
MCU: stm32f446RETx

It appears the CRC peripheral always emits a computed value of zero, regardless of the bytes feed to it.

reproducible sample
```rs
#![deny(unsafe_code)]
#![no_main]
#![no_std]

// panic via probe
use panic_probe as _;

use cortex_m;
use cortex_m_rt::entry;
use stm32f4xx_hal::{prelude::*, crc32, stm32};

use rtt_target::{rtt_init_print, rprintln};

static BUFFER: [u8; 4] = [0x32u8, 0x42u8, 0x12u8, 0x44u8];

#[entry]
fn main() -> ! {
    rtt_init_print!();
    rprintln!("hello, world!");
    if let Some(dp) = stm32::Peripherals::take() {
        // Set up the system clock.
        let rcc = dp.RCC.constrain();

        // Initialize the CRC32 peripheral
        let mut crc = crc32::Crc32::new(dp.CRC);
        // declare a buffer
        let result = crc.update_bytes(&BUFFER);
        rprintln!("crc32 of {:?} = {}", BUFFER, result);
    }

    loop {
        cortex_m::asm::nop();
    }
}
```
Expected result:
```
hello, world!
crc32 of [50, 66, 18, 68] = 2252567011
```
Actual Result:
```
hello, world!
crc32 of [50, 66, 18, 68] = 0
```

### PR DESCRIPTION
**Pull request by theunkn0wn1**
The current implementation of the CRC32 perhipheral does not enable the CRC32 clock.
On the STM32F446﻿, this causes **all** calculations against this peripheral to emit an incorrect null instead of the checksum.

This PR enables the CRC clock when the HAL's peripheral is acquired, and disables it when released.

Fixes #281

### CODE REVIEW

File: src/crc32.rs [hunk 1]
```diff
@@ -21,6 +21,14 @@ impl Crc32 {
     pub fn new(crc: CRC) -> Self {
         let mut new = Self { periph: crc };
         new.init();
+
+        unsafe {
+            // NOTE(unsafe) this reference will only be used for atomic writes with no side effects.
+            let rcc_raw = unsafe { &(*RCC::ptr()) };
+            // Enable CRC clock
+            rcc_raw.ahb1enr.modify(|_, w| w.crcen().enabled());
```
Comment (therealprof) [inline src/crc32.rs:29]: Please use bitbanding to change the flag instead, cf. `gpio.rs`.

Also after enabling the clocks, you might want to throw in a `cortex_m::asm::dsb();` for good measure to work around an erratum, also cf. `gpio.rs`.

Comment (theunkn0wn1) [reply src/crc32.rs]: Done.

File: src/crc32.rs [hunk 2]
```diff
@@ -111,6 +121,14 @@ impl Crc32 {
 
     /// Consume the HAL peripheral, returning the PAC peripheral
     pub fn free(self) -> CRC {
+        unsafe {
+            // NOTE(unsafe) this reference will only be used for atomic writes with no side effects.
+            let rcc_raw = unsafe { &(*RCC::ptr()) };
```
Comment (thalesfragoso) [inline src/crc32.rs:126]: This is already inside a unsafe block, so the second unsafe is unnecessary and emits a warning.

File: src/crc32.rs [hunk 3]
```diff
@@ -111,6 +121,14 @@ impl Crc32 {
...
+            // Disable CRC clock
+            bb::write(&rcc_raw.ahb1enr, 12, false);
```
Comment (thalesfragoso) [inline src/crc32.rs:128]: Might be better to use `bb::clear` ?

File: src/crc32.rs [hunk 4]
```diff
@@ -21,6 +23,15 @@ impl Crc32 {
     pub fn new(crc: CRC) -> Self {
         let mut new = Self { periph: crc };
         new.init();
+
+        unsafe {
+            // NOTE(unsafe) this reference will only be used for atomic writes with no side effects.
+            let rcc_raw = unsafe { &(*RCC::ptr()) };
```
Comment (thalesfragoso) [inline src/crc32.rs:29]: This is already inside a unsafe block, so the second unsafe is unnecessary and emits a warning.

File: src/crc32.rs [hunk 5]
```diff
@@ -21,6 +23,15 @@ impl Crc32 {
...
+            // CRCEN = true; enable CRC clock.
+            bb::write(&rcc_raw.ahb1enr, 12, true);
```
Comment (thalesfragoso) [inline src/crc32.rs:31]: Might be better to use `bb::set` ?

File: src/crc32.rs [hunk 6]
```diff
@@ -21,6 +23,15 @@ impl Crc32 {
     pub fn new(crc: CRC) -> Self {
         let mut new = Self { periph: crc };
         new.init();
```
Comment (thalesfragoso) [inline src/crc32.rs:25]: You probably want to enable the clocks before this.

**Review by thalesfragoso — CHANGES_REQUESTED** [review]
Thanks for spotting the problem and providing a solution! I left a few suggestions.

File: src/crc32.rs (hunk 3 above)
Comment (theunkn0wn1) [reply src/crc32.rs:128]: Probably right. Adjusted.

File: src/crc32.rs (hunk 2 above)
Comment (theunkn0wn1) [reply src/crc32.rs:126]: Oops! will correct.

File: src/crc32.rs (hunk 6 above)
Comment (theunkn0wn1) [reply src/crc32.rs]: Moved to be the first thing `Crc32::new` does. I don't believe it makes a considerable difference as calculations arn't done until the first write to the data register; which occurs outside this constructor.

File: src/crc32.rs (hunk 4 above)
Comment (theunkn0wn1) [reply src/crc32.rs]: Corrected.

File: src/crc32.rs (hunk 6 above)
Comment (thalesfragoso) [reply src/crc32.rs]: Thanks, the difference was that the `init` was resetting an internal state, which probably wouldn't do anything with the clocks disabled.

Comment (theunkn0wn1) [reply src/crc32.rs]: The implementation of `init` sets the `RESET` bit of `CRC_CR`, which is automatically cleared by the hardware.
Even if the reset doesn't occur until after the clock is enabled, I suspect the device would still be reset.

Either way, its a fair point and I have no problem enabling the clock earlier.

**Review by thalesfragoso — APPROVED** [review]
Thanks again!

bors r+
