### PR TITLE
Errata workaround: Removing error return on I2C bus error detection

### LINKED ISSUE #274: Spurious I2C bus errors occur
Due to errata in the STM32F4 I2C implementation, the I2C module may spuriously (and erroneously) indicate bus errors.

image

We should likely just throw out the BERR bit status instead of indicating incorrect errors, as advised by the errata.

The erratum is found in the following Errata sheets
Reference:
* [F42xx Errata](https://www.st.com/resource/en/errata_sheet/dm00068628-stm32f427437-and-stm32f429439-line-limitations-stmicroelectronics.pdf)
* [F40xx/F41xx Errata](https://www.st.com/resource/en/errata_sheet/dm00037591-stm32f405407xx-and-stm32f415417xx-device-limitations-stmicroelectronics.pdf)
* [STM32F46x/STM32F47x Errata](https://www.st.com/resource/en/errata_sheet/dm00220774-stm32f469xx-and-stm32f479xx-device-errata-stmicroelectronics.pdf)
* [F44x Errata](https://www.st.com/resource/en/errata_sheet/dm00155929-stm32f446xcxe-device-limitations-stmicroelectronics.pdf)

### PR DESCRIPTION
**Pull request by ryan-summers**
As outlined in #274, the I2C module may indicate spurious bus errors. This PR removes the `Error::BUS` variant from the I2C interface and updates the status flags check to ignore BERR bit assertions.

This fixes #274 

TODO:
- [x] I'm testing this update on our hardware to verify that it resolves our spurious reset issue

### CODE REVIEW

File: src/i2c.rs [hunk 1]
```diff
@@ -551,7 +551,6 @@ pub enum Error {
     OVERRUN,
     NACK,
     TIMEOUT,
-    BUS,
```
Comment (therealprof) [inline src/i2c.rs:554]: Can we leave this in there? I'd rather not break existing applications for no good reason.

Comment (ryan-summers) [reply src/i2c.rs:554]: Yeah, I'm happy to. I'll add a ntoe that this error type is only maintained for backwards compatibility.

**Comment by therealprof** [comment]
Is this ready for merge yet or do you want to do the testing first? Could you squash your commits?

**Comment by ryan-summers** [comment]
@therealprof This should be good-to-go. Hardware tests look fine and I've squashed the commits.

The TODO isn't necessarily related, as that's for a different project, so I've marked it as complete. Sorry for the confusion.

**Review by therealprof — APPROVED** [review]
LGTM, thanks.

bors r+
